// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import ic "github.com/calionauta/gogogo/internal/components"

// RealtimeStream opens the persistent Server-Sent Events stream that keeps
// every connected browser in sync. It is rendered ONCE, from Layout, so the
// realtime wiring lives in exactly one place and cannot drift per-page.
//
// WHY THE HIDDEN-BUTTON + SCRIPT PATTERN (not data-on:load):
// Datastar v1 does not fire data-on:load / data-on:init on <div> or <body>,
// so a card using `data-on:load={ "@get('/api/todos/stream') }` silently
// never opened the stream — broadcasts were registered on the server but no
// browser ever received them, and the connected-clients count stayed wrong.
// The fix is a hidden button whose data-on:click is a real @get (Datastar
// keeps that open as a persistent SSE), clicked by this script once Datastar
// signals readiness. Centralising it here means a single regression test can
// assert the opener + script are present on every page.
//
// CLIENT ID (the realtime identity):
// Each browser TAB gets a stable clientID, persisted in sessionStorage so a
// reload keeps the same id (and thus keeps its SSE registration instead of
// leaking a new one). The SSE stream is opened WITH that clientID, and every
// todo mutation POSTs the SAME clientID. The server uses it for
// BroadcastExcept, so the originator is excluded from the re-render while
// EVERY OTHER tab (focused or backgrounded) receives the broadcast. Without
// the shared id, mutations can't be excluded from the originator and other
// tabs silently miss updates.
//
// VISIBILITY-RESILIENT RECONNECT:
// Browsers throttle/pause EventSource when a tab is backgrounded, so a
// backgrounded tab can miss SSE frames. We listen for visibilitychange and
// re-open the stream when the tab becomes visible again (Datastar dedupes
// duplicate permanent streams, and the server's replay buffer replays
// events the tab missed while hidden). This makes realtime work regardless
// of which tab/window currently has focus — the user never has to be
// looking at the tab to receive updates.
//
// streamURL is the SSE endpoint to open (e.g. "/api/todos/stream"). Other
// features pass their own endpoint; the mechanism is identical.
func RealtimeStream(streamURL string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button id=\"sse-opener\" class=\"hidden\" data-on:click=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue("@get('" + streamURL + "?clientID=' + encodeURIComponent(window.__gogogoClientID || '') + '', { permanent: true })")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `features/todo/components/realtime.templ`, Line: 44, Col: 133}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" aria-hidden=\"true\"></button><script type=\"module\">\n\t\t// Stable per-tab client id. Persisted in sessionStorage so a reload\n\t\t// reuses the same id (no leaked SSE registration on the server) and\n\t\t// every mutation POSTs the matching id for BroadcastExcept.\n\t\t(function () {\n\t\t\ttry {\n\t\t\t\tvar id = sessionStorage.getItem('gogogo_client_id');\n\t\t\t\tif (!id) {\n\t\t\t\t\tid = 'tab-' + Math.random().toString(36).slice(2, 10);\n\t\t\t\t\tsessionStorage.setItem('gogogo_client_id', id);\n\t\t\t\t}\n\t\t\t\twindow.__gogogoClientID = id;\n\t\t\t} catch (e) {\n\t\t\t\twindow.__gogogoClientID = 'tab-' + Math.random().toString(36).slice(2, 10);\n\t\t\t}\n\n\t\t\tfunction openSSE() {\n\t\t\t\tvar b = document.getElementById('sse-opener');\n\t\t\t\tif (b && !b.dataset.opened) { b.dataset.opened = '1'; b.click(); }\n\t\t\t}\n\t\t\tdocument.addEventListener('datastar-ready', openSSE);\n\t\t\t// Fallback if datastar-ready already fired.\n\t\t\tsetTimeout(openSSE, 300);\n\n\t\t\t// Re-open when the tab returns to the foreground: backgrounded\n\t\t\t// tabs have their EventSource throttled/paused by the browser, so\n\t\t\t// they can miss frames. Re-clicking the opener makes Datastar\n\t\t\t// re-establish the permanent stream (the server replays missed\n\t\t\t// events via its buffer). This keeps realtime working for tabs the\n\t\t\t// user is NOT currently looking at.\n\t\t\tdocument.addEventListener('visibilitychange', function () {\n\t\t\t\tif (!document.hidden) {\n\t\t\t\t\tvar b = document.getElementById('sse-opener');\n\t\t\t\t\tif (b) { b.dataset.opened = ''; openSSE(); }\n\t\t\t\t}\n\t\t\t});\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// PbRealtimeRecords subscribes to PocketBase realtime for the `todos`
// collection and re-renders the list region on any record change. This is
// the "records" half of the "best of both" realtime strategy:
//   - RECORDS (todo create/update/delete) flow through PocketBase realtime,
//     which is per-user scoped — PB only delivers records the subscriber can
//     see, so there is no cross-user broadcast leak (the old hub broadcast
//     to every connected client regardless of owner).
//   - EPHEMERAL signals (retry feedback, suggest, workflow progress) keep
//     flowing through the SSE hub (see RealtimeStream), which is in-process
//     and supports BroadcastExcept (exclude-origin) for those signals.
//
// We use the NATIVE EventSource + fetch subscribe protocol (no PocketBase
// JS SDK dependency): the browser sends the pb_auth cookie automatically on
// the SSE GET, PocketBase authenticates, and we POST the subscribe body. On
// a record mutation event we re-fetch the list fragment via Datastar's
// programmatic @get (window.datastar.get), morphing #todo-list in place.
func PbRealtimeRecords() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ic.PbRealtimeResync("pb-realtime-resync", "'/api/todos/fragment?filter=' + encodeURIComponent($filter || 'all')", "todos").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = DocVersionWatcher().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// DocVersionWatcher re-fetches the list when the SSE hub fans out a
// doc-version-bumped event (CRDTStore peer write). Split out of
// PbRealtimeRecords so the shared resync component stays generic:
// record changes go through PB realtime, doc-version bumps through
// this watcher, both ending on the same hidden @get button.
func DocVersionWatcher() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<script type=\"module\">\n\t\t// CRDTStore doc-version watcher (Phase 3).\n\t\t//\n\t\t// When the SSE hub fans out a doc-version-bumped event\n\t\t// (from a peer instance via ApplyRemoteOp OR from a local\n\t\t// CRDTStore mutation), the server merges the $docVersion\n\t\t// signal on this client. We watch that signal and\n\t\t// re-fetch the fragment — same path as a PB record event,\n\t\t// so the UX is identical regardless of which side wrote.\n\t\t//\n\t\t// We poll because Datastar v1 does not expose a signal-\n\t\t// change subscribe API; the signal lives on a document\n\t\t// attribute managed by Datastar. A 250ms tick is cheap\n\t\t// (one number compare) and well under human perception.\n\t\tfunction clickResync() {\n\t\t\tvar b = document.getElementById(\"pb-realtime-resync\");\n\t\t\tif (b) { b.click(); }\n\t\t}\n\t\tvar lastDocVersion = null;\n\t\tfunction watchDocVersion() {\n\t\t\tvar sig = document.body && document.body.getAttribute(\"data-signals-docVersion\");\n\t\t\tvar v = sig == null ? null : Number(sig);\n\t\t\tif (v != null && v !== lastDocVersion) {\n\t\t\t\tlastDocVersion = v;\n\t\t\t\tif (window.__gogogoDocVersionReady) { clickResync(); }\n\t\t\t\twindow.__gogogoDocVersionReady = true;\n\t\t\t}\n\t\t}\n\t\tdocument.addEventListener(\"datastar-ready\", function () {\n\t\t\twatchDocVersion();\n\t\t\tsetInterval(watchDocVersion, 250);\n\t\t});\n\t\tsetTimeout(function () {\n\t\t\twatchDocVersion();\n\t\t\tsetInterval(watchDocVersion, 250);\n\t\t}, 400);\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
