// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
// SCOPE:core - shared PocketBase-realtime list resync (records half).

package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// PbRealtimeResync subscribes to PocketBase realtime for one collection
// name and re-fetches a list fragment on any record change. This is the
// "records" half of the realtime strategy (record mutations are per-user
// scoped by PB, so there is no cross-user broadcast leak); ephemeral
// signals keep flowing through the SSE hub. Rendered ONCE per page.
//
// the button id must be unique on the page (each page's id is pinned by its
// feature test). fragmentExpr is the Datastar @get argument as
// client-side JS (e.g. a fragment path) — evaluated by Datastar
// at click time, never by the server. The last argument is the PB subscription name.
//
// The script finds its button through the data-pb-resync marker (never
// a second copy of the id) and reads that name back with getAttribute:
// Templ never interpolates Go values inside <script> bodies, so values
// cross that boundary only as data attributes.
//
// clientID reuses the stable per-tab id when RealtimeStream set one,
// else a fresh random id — the same behavior the per-feature copies had.
func PbRealtimeResync(buttonID, fragmentExpr, topic string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(buttonID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/realtime_resync.templ`, Line: 24, Col: 15}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" type=\"button\" class=\"hidden\" data-on:click=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue("@get(" + fragmentExpr + ")")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/realtime_resync.templ`, Line: 27, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" data-pb-resync=\"1\" data-topic=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(topic)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/realtime_resync.templ`, Line: 29, Col: 20}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" aria-hidden=\"true\"></button><script type=\"module\">\n\t\t// Hidden-@get-button + EventSource pattern (not data-on:load):\n\t\t// Datastar v1 does not fire data-on:load on div/body, so a load\n\t\t// attribute silently never opens anything. The button's @get is a\n\t\t// real Datastar action (with proper context); this script clicks it.\n\t\tfunction el() { return document.querySelector('[data-pb-resync]'); }\n\t\tfunction subj() {\n\t\t\tvar b = el();\n\t\t\treturn b ? b.getAttribute('data-topic') : null;\n\t\t}\n\t\tvar cid = window.__gogogoClientID || ('tab-' + Math.random().toString(36).slice(2, 10));\n\t\tvar es = new EventSource('/api/realtime?clientId=' + encodeURIComponent(cid));\n\t\tfunction sub(id) {\n\t\t\tfetch('/api/realtime', {\n\t\t\t\tmethod: 'POST',\n\t\t\t\theaders: { 'Content-Type': 'application/json' },\n\t\t\t\tbody: JSON.stringify({ clientId: id, action: 'subscribe', subscriptions: [subj()] })\n\t\t\t}).catch(function () {});\n\t\t}\n\t\tfunction go() {\n\t\t\tvar b = el();\n\t\t\tif (b) { b.click(); }\n\t\t}\n\t\tes.addEventListener('PB_CONNECT', function (e) {\n\t\t\tvar msg;\n\t\t\ttry { msg = JSON.parse(e.data); } catch (_) { return; }\n\t\t\tif (!msg.clientId) { return; }\n\t\t\t// PocketBase sends RECORD events on `event: <name>`, NOT on\n\t\t\t// the clientId channel (which carries only control messages\n\t\t\t// like PB_CONNECT / PB_SUBSCRIBED).\n\t\t\tes.addEventListener(subj(), function () { go(); });\n\t\t\tsub(msg.clientId);\n\t\t\t// Refetch: PB realtime has NO replay buffer, so a change from\n\t\t\t// before the subscription went live would otherwise never\n\t\t\t// arrive. Same on tab-visibility return (backgrounded tabs get\n\t\t\t// their EventSource throttled/paused by the browser).\n\t\t\tgo();\n\t\t});\n\t\tdocument.addEventListener('visibilitychange', function () {\n\t\t\tif (!document.hidden) { go(); }\n\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
