// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
// SCOPE:core - shared toast stacking container.

package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// ToastContainer renders the fixed bottom-right stacking container plus
// the toast entrance/progress CSS that ic.Toast depends on. Any page
// whose server code patches #toast-container (emitToast and friends)
// must render this — without it every toast errors with
// PatchElementsNoTargetsFound and vanishes silently (lived bug on the
// Ask page, latent on the basecoat skin). One definition, not one copy
// per layout: the todo Layout keeps its own identical block for now
// (byte-stability on the most-tested page; consolidate on next touch).
func ToastContainer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t#toast-container {\n\t\t\tz-index: 100;\n\t\t\tposition: fixed;\n\t\t\tright: 1rem;\n\t\t\tbottom: 1rem;\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column-reverse;\n\t\t\tgap: 0.5rem;\n\t\t\tmax-width: 24rem;\n\t\t}\n\t\t.toast-msg {\n\t\t\topacity: 0;\n\t\t\ttransform: scale(0.9) translateY(50px);\n\t\t\ttransition: transform 0.5s, opacity 0.5s;\n\t\t}\n\t\t.toast-msg.open {\n\t\t\ttransform: scale(1) translateY(0);\n\t\t\topacity: 1;\n\t\t}\n\t\t.toast-timer-bar {\n\t\t\theight: 3px;\n\t\t\tborder-radius: 999px;\n\t\t\tbackground: oklch(0.872 0.01 258.338 / 0.3);\n\t\t\tanimation: toast-shrink 3s linear forwards;\n\t\t}\n\t\t.toast-msg:has(.alert-error) .toast-timer-bar {\n\t\t\tanimation-duration: 8s;\n\t\t}\n\t\t@keyframes toast-shrink {\n\t\t\tfrom { width: 100%; }\n\t\t\tto { width: 0%; }\n\t\t}\n\t</style><div id=\"toast-container\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
