#!/usr/bin/env python3
"""Rename this template's project identity in one verified pass.

This repo is a GitHub *template* (`is_template: true`). Clicking "Use this
template" gives you a copy that still says `gogogo-fullstack-template`
everywhere: the Go module path, the binary name, the container name, the
titles, the deploy paths. That is hundreds of occurrences across ~200 files
(the exact count drifts as the template grows — this script prints the current
one, so trust its output rather than a number written here), and doing it by
hand invites a half-renamed tree that compiles but deploys to the wrong
directory.

This script does the whole substitution and then *proves* it worked by building.

Usage:
    python3 scripts/rename-project.py <new-name> [--owner <gh-owner>] [--dry-run]

    make rename NAME=my-app
    make rename NAME=my-app OWNER=myorg
    make rename NAME=my-app DRY=1

What it rewrites (tracked files only — build artifacts and databases are
ignored by construction, because `git ls-files` is the file list):

    1. the Go module path      github.com/<owner>/gogogo-fullstack-template
                            -> github.com/<owner>/<new-name>
    2. the bare project name   gogogo-fullstack-template -> <new-name>
    3. the Pages host          <owner>.github.io -> <new-owner>.github.io

Step 1 runs first so the module path is fixed before the bare-name pass, and
step 3 is skipped unless --owner changes the account.

Deliberately NOT touched:
    - site/docs/, site/llms*.txt, site/sitemap.xml — generated by
      site/build.mjs. Run `make site` afterwards to regenerate them.
    - this script itself — so it stays usable for a second rename.
    - .git history, tags, releases — a rename is a working-tree operation.

Exit codes: 0 on success (or a clean dry-run), 1 on a bad invocation, 2 when
the post-rename build fails (the tree is left renamed; the error tells you
what broke).
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

OLD_NAME = "gogogo"
OLD_OWNER = "calionauta"
OLD_MODULE = f"github.com/{OLD_OWNER}/{OLD_NAME}"

# The short name is a substring of unrelated identifiers, so a bare
# `text.replace(OLD_NAME, new_name)` corrupts them. Two classes matter:
#
#   gogogo_auth, gogogo_client_id, gogogo_sound, gogogo_cid
#       internal identifiers (cookie name, sound preference key, SSE client
#       id). Renaming them would be a behaviour change with no benefit, and
#       would desync any browser that still holds the old cookie.
#
#   window.__gogogoClientID, __gogogo_add, __gogogo_clr, ...
#       JavaScript globals. A hyphenated project name produces
#       `window.__my-appClientID`, which is not valid JS at all.
#
#   gogogo.calionauta.com
#       the template author's own hostname. Not the user's, so it stays.
#
# These are shielded with placeholders before substitution and restored after,
# the same technique already used for FOREIGN_REPOS. Anything matching
# `OLD_NAME` followed by a word character or a dot-then-word boundary is a
# longer identifier, not the project name.
SHIELDED_IDENTIFIERS = (
    "gogogo_auth",
    "gogogo_sound",
    "gogogo_client_id",
    "gogogo_cid",
    "gogogo_live",
    "gogogo__queued",
    "__gogogo_add",
    "__gogogo_clr",
    "__gogogo_del",
    "__gogogo_tog",
    "__gogogoClientID",
    "__gogogoDocVersionReady",
    "__gogogoSSEWired",
    f"{OLD_NAME}.calionauta.com",
)

# Generated by site/build.mjs — never hand-edited, so never rewritten here.
# Prefixes are matched against repo-relative paths.
GENERATED_PREFIXES = (
    "site/docs/",
    "site/llms.txt",
    "site/llms-full.txt",
    "site/sitemap.xml",
)

# Third-party and sibling repos under the same owner that must NEVER be
# rewritten when --owner changes. `github.com/calionauta/ai-credits` is a real
# dependency; turning it into `github.com/myorg/ai-credits` breaks the build and
# points at a repo that does not exist. Only OUR repo name is substituted.
FOREIGN_REPOS = (
    "github.com/calionauta/ai-credits",
    "github.com/calionauta/datastar-lint",
    "github.com/calionauta/pi-leakguard",
)

# Valid GitHub repo name: letters, digits, hyphen, underscore, dot; must start
# with a letter or digit. Enforced because the name becomes a Go module path
# segment and a container/image name — a bad character fails much later, in a
# much more confusing place.
NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")

# This script must keep working if run twice, so it is not self-rewriting.
SELF = "scripts/rename-project.py"


def repo_root() -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=False,
    )
    if out.returncode != 0:
        sys.exit("error: not inside a git repository")
    return Path(out.stdout.strip())


def tracked_files(root: Path) -> list[str]:
    """Tracked paths only. This is what makes the rewrite safe: artifacts,
    local databases, built binaries and coverage files are untracked and are
    therefore never candidates."""
    out = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    )
    return [p for p in out.stdout.split("\0") if p]


def is_text(path: Path) -> bool:
    """Cheap binary sniff. The repo has .db, .png and built binaries tracked
    in some checkouts; rewriting those would corrupt them."""
    try:
        with path.open("rb") as fh:
            chunk = fh.read(8192)
    except OSError:
        return False
    return b"\0" not in chunk


def plan_replacement(text: str, new_name: str, new_owner: str) -> str:
    """Order matters: the module path contains the bare name, so fixing the
    module first means the bare-name pass never has to reason about it.

    The owner substitution is intentionally narrow. Only OUR repo is re-pointed
    at the new owner — never `github.com/<owner>/<other-repo>`, because those are
    real dependencies (ai-credits, datastar-lint, pi-leakguard) that live under
    the original owner and would 404 if rewritten.
    """
    # Shield things that must survive every pass, then restore them at the end.
    # Two groups: real dependencies under the same owner, and identifiers that
    # merely CONTAIN the old name (see SHIELDED_IDENTIFIERS for why renaming
    # those is wrong).
    placeholders: dict[str, str] = {}
    for i, repo in enumerate(FOREIGN_REPOS):
        token = f"\x00FOREIGN{i}\x00"
        if repo in text:
            placeholders[token] = repo
            text = text.replace(repo, token)

    # Longest first, so `__gogogoClientID` is shielded before the shorter
    # `gogogo` prefix inside it could be rewritten by an earlier match.
    for i, ident in enumerate(sorted(SHIELDED_IDENTIFIERS, key=len, reverse=True)):
        token = f"\x00IDENT{i}\x00"
        if ident in text:
            placeholders[token] = ident
            text = text.replace(ident, token)

    text = text.replace(OLD_MODULE, f"github.com/{new_owner}/{new_name}")

    if new_owner != OLD_OWNER:
        # Bare owner/repo references (README links, blob URLs) for OUR repo.
        text = text.replace(f"{OLD_OWNER}/{OLD_NAME}", f"{new_owner}/{new_name}")
        # Pages host, e.g. calionauta.github.io -> myorg.github.io.
        text = text.replace(f"{OLD_OWNER}.github.io", f"{new_owner}.github.io")

    text = text.replace(OLD_NAME, new_name)

    for token, original in placeholders.items():
        text = text.replace(token, original)
    return text


def count_changes(original: str, updated: str) -> int:
    """Count how many occurrences actually changed.

    Counting needles in the ORIGINAL text (the obvious approach) undercounts:
    a `--owner` run rewrites `calionauta.github.io` and `calionauta/<repo>`
    without touching the bare name, so a file that only carries those reported
    zero while still being modified. Counting the common suffix between the two
    strings is wrong too. This compares line by line instead — every line that
    differs is at least one change, which is what the reader wants to know.
    """
    if original == updated:
        return 0
    before = original.splitlines()
    after = updated.splitlines()
    if len(before) != len(after):
        return max(len(before), len(after))
    return sum(1 for a, b in zip(before, after) if a != b)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Rename this template's project identity.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("name", help="new project name (e.g. my-app)")
    ap.add_argument(
        "--owner",
        default=OLD_OWNER,
        help=f"GitHub owner/org for the module path (default: {OLD_OWNER})",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="show what would change, write nothing",
    )
    args = ap.parse_args()

    new_name, new_owner = args.name.strip(), args.owner.strip()

    if not NAME_RE.match(new_name):
        sys.exit(
            f"error: invalid name {new_name!r} — must start with a letter or "
            "digit and contain only letters, digits, dot, hyphen, underscore"
        )
    if new_name == OLD_NAME and new_owner == OLD_OWNER:
        sys.exit("error: nothing to do — the name and owner are unchanged")

    root = repo_root()
    files = tracked_files(root)

    changed: list[tuple[str, int]] = []
    skipped_generated = 0
    skipped_binary = 0

    for rel in files:
        if rel == SELF:
            continue
        if rel.startswith(GENERATED_PREFIXES):
            skipped_generated += 1
            continue

        path = root / rel
        if not is_text(path):
            skipped_binary += 1
            continue

        try:
            original = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            skipped_binary += 1
            continue

        updated = plan_replacement(original, new_name, new_owner)
        if updated == original:
            continue

        hits = count_changes(original, updated)
        changed.append((rel, hits))
        if not args.dry_run:
            path.write_text(updated, encoding="utf-8")

    total_hits = sum(h for _, h in changed)

    if not changed:
        print(f"nothing to change — no occurrence of {OLD_NAME!r} found.")
        return 0

    verb = "would rewrite" if args.dry_run else "rewrote"
    print(f"{verb} {total_hits} occurrence(s) in {len(changed)} file(s):")
    for rel, hits in sorted(changed, key=lambda t: -t[1])[:20]:
        print(f"  {hits:>4}  {rel}")
    if len(changed) > 20:
        print(f"        … and {len(changed) - 20} more")
    if skipped_generated:
        print(f"\nskipped {skipped_generated} generated file(s) (run `make site`)")
    if skipped_binary:
        print(f"skipped {skipped_binary} non-text file(s)")

    if args.dry_run:
        print("\ndry run — nothing written.")
        return 0

    print(f"\nmodule path : github.com/{new_owner}/{new_name}")
    print(f"project name: {new_name}")

    # Prove it. A rename that leaves a stale import compiles nowhere, and the
    # failure is much cheaper to read here than in CI.
    print("\nverifying: go build ./cmd/web …")
    build = subprocess.run(
        ["go", "build", "-o", os.devnull, "./cmd/web"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if build.returncode != 0:
        print(build.stderr.strip()[:2000], file=sys.stderr)
        print(
            "\nerror: the rename is applied but the build fails — fix the error "
            "above (it usually names a stale import the substitution missed).",
            file=sys.stderr,
        )
        return 2
    print("build OK")

    print(
        "\nnext:\n"
        "  1. make site        # regenerate site/docs/ + llms.txt + sitemap.xml\n"
        "  2. review the diff  # git diff --stat\n"
        "  3. update the deploy secrets/hostname if you deploy\n"
        "     (see docs/deploy.md — APP_NAME drives the server directory)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
